#!/bin/bash

set -e
cd "/Users/ej/Super-Legal/super-legal-mcp-refactored/reports/2026-01-22-1737576000"

echo "=== FINAL INTEGRATION - W6-001 ==="

cp remediation-outputs/W3-XREF-INSERT-final-memorandum-xrefs.md /tmp/base.md

echo "[1] Extract base components..."
sed -n '1,174p' /tmp/base.md > /tmp/header.txt
sed -n '242,371p' /tmp/base.md > /tmp/sec-II-risk.txt
sed -n '372,745p' /tmp/base.md > /tmp/sec-III-matrix.txt
sed -n '746,$p' /tmp/base.md > /tmp/sec-IV-detail.txt

echo "[2] Extract ONLY Section I from W4-002 (lines 13-74, before Section II)..."
sed -n '13,74p' remediation-outputs/W4-002-exec-summary-condensed.md > /tmp/exec-summary-only.txt

echo "[3] Assemble final document..."

{
  # Header
  cat /tmp/header.txt
  
  echo ""
  echo "## I. EXECUTIVE SUMMARY / BOARD BRIEFING"
  echo ""
  
  # Executive summary (ONLY Section I.A and I.B from W4-002)
  cat /tmp/exec-summary-only.txt
  
  echo ""
  echo "---"
  echo ""
  
  # NEW Section II: Questions Presented
  echo "## II. QUESTIONS PRESENTED"
  echo ""
  sed -n '12,$p' remediation-outputs/W2-001-questions-presented.md
  echo ""
  echo "---"
  echo ""
  
  # NEW Section III: Brief Answers
  echo "## III. BRIEF ANSWERS"
  echo ""
  sed -n '7,$p' remediation-outputs/W2-002-brief-answers.md
  echo ""
  echo "---"
  echo ""
  
  # RENUMBERED Section IV: Aggregate Risk (was Section II)
  echo "## IV. AGGREGATE RISK SUMMARY"
  echo ""
  tail -n +2 /tmp/sec-II-risk.txt
  echo ""
  echo "---"
  echo ""
  
  # RENUMBERED Section V: Critical Issues Matrix (was Section III)
  echo "## V. CRITICAL ISSUES MATRIX"
  echo ""
  tail -n +2 /tmp/sec-III-matrix.txt
  echo ""
  echo "---"
  echo ""
  
  # RENUMBERED Section VI: Detailed Legal Analysis (was Section IV)
  echo "## VI. DETAILED LEGAL ANALYSIS"
  echo ""
  tail -n +2 /tmp/sec-IV-detail.txt
  
} > /tmp/integrated.md

echo "[4] Apply W4-001 neutral language..."
sed 's/clearly sufficient/sufficient under precedent/g' /tmp/integrated.md > /tmp/neutral.md

echo "[5] Update cross-references for renumbering..."
sed -e 's/\(Section \)II\(\.[^A-Z]\)/\1IV\2/g' \
    -e 's/\(Section \)III\(\.[^A-Z]\)/\1V\2/g' \
    -e 's/(Section II\./(Section IV./g' \
    -e 's/(Section III\./(Section V./g' \
    /tmp/neutral.md > /tmp/xref.md

echo "[6] Add document footer..."

{
  cat /tmp/xref.md
  echo ""
  echo "═══════════════════════════════════════════════════════════════════════════════"
  echo "                          END OF MEMORANDUM"
  echo "═══════════════════════════════════════════════════════════════════════════════"
  echo ""
  echo "RESEARCH SUMMARY DISCLAIMER: This document is a research summary generated by"
  echo "an AI legal research platform. It is NOT legal advice from a licensed attorney."
  echo "All findings require independent verification by qualified legal counsel."
} > final-memorandum-v2.md

echo ""
echo "=== COMPLETE ==="
echo "File size: $(wc -lw final-memorandum-v2.md)"
echo ""
echo "Main section headers:"
grep -n "^## [IVX]*\." final-memorandum-v2.md | grep -E "^[0-9]+:## (I|II|III|IV|V|VI)\." | head -12
echo ""
echo "Word count: $(wc -w < final-memorandum-v2.md) words"
echo ""
echo "Integration complete!"

