#!/bin/bash

set -e
WORK_DIR="/Users/ej/Super-Legal/super-legal-mcp-refactored/reports/2026-01-22-1737576000"
cd "$WORK_DIR"

echo "=== W6-001 Integration Script (Fixed) ==="

# Start fresh from W3-XREF base
cp remediation-outputs/W3-XREF-INSERT-final-memorandum-xrefs.md /tmp/base.md

# Extract components
echo "[1] Extracting document header (lines 1-174)..."
sed -n '1,174p' /tmp/base.md > /tmp/header.txt

echo "[2] Extracting original Section I (Executive Summary, lines 175-241)..."
# We will REPLACE this entirely with W4-002 content

echo "[3] Extracting original Section II (Aggregate Risk, lines 242-371)..."
sed -n '242,371p' /tmp/base.md > /tmp/old-sec-II.txt

echo "[4] Extracting original Section III (Critical Issues, lines 372-745)..."
sed -n '372,745p' /tmp/base.md > /tmp/old-sec-III.txt

echo "[5] Extracting original Section IV+ (Detailed Analysis, line 746-end)..."
sed -n '746,$p' /tmp/base.md > /tmp/old-sec-IV.txt

echo "[6] Building new memorandum structure..."

{
  # Document header (title, caption, TOC)
  cat /tmp/header.txt
  
  echo ""
  echo "## I. EXECUTIVE SUMMARY / BOARD BRIEFING"
  echo ""
  
  # Insert W4-002 condensed executive summary content
  # Skip first 12 lines (title block) and subsection headers with Roman numerals
  sed -n '13,$p' remediation-outputs/W4-002-exec-summary-condensed.md | \
  sed 's/^## I\. /### A. /' | \
  sed 's/^## I\.B\. /### B. /' | \
  sed 's/^## II\. /### C. /' | \
  sed 's/^## III\. /### D. /' | \
  sed 's/^## IV\. /### E. /' | \
  sed 's/^## V\. /### F. /' | \
  sed 's/^## VI\. /### G. /' | \
  sed 's/^## VII\. /### H. /' | \
  sed 's/^## VIII\. /### I. /' | \
  sed 's/^## IX\. /### J. /'
  
  echo ""
  echo "---"
  echo ""
  
  # NEW Section II: Questions Presented (W2-001)
  echo "## II. QUESTIONS PRESENTED"
  echo ""
  # Skip first 11 lines of W2-001 (title block)
  sed -n '12,$p' remediation-outputs/W2-001-questions-presented.md
  echo ""
  echo "---"
  echo ""
  
  # NEW Section III: Brief Answers (W2-002)
  echo "## III. BRIEF ANSWERS"
  echo ""
  # Skip first 6 lines of W2-002 (title block)
  sed -n '7,$p' remediation-outputs/W2-002-brief-answers.md
  echo ""
  echo "---"
  echo ""
  
  # RENUMBERED Section IV: Aggregate Risk Summary (was II)
  echo "## IV. AGGREGATE RISK SUMMARY"
  echo ""
  # Remove first line (old header)
  tail -n +2 /tmp/old-sec-II.txt
  echo ""
  echo "---"
  echo ""
  
  # RENUMBERED Section V: Critical Issues Matrix (was III)
  echo "## V. CRITICAL ISSUES MATRIX"
  echo ""
  tail -n +2 /tmp/old-sec-III.txt
  echo ""
  echo "---"
  echo ""
  
  # RENUMBERED Section VI: Detailed Legal Analysis (was IV)
  echo "## VI. DETAILED LEGAL ANALYSIS"
  echo ""
  tail -n +2 /tmp/old-sec-IV.txt
  
} > /tmp/integrated-step1.md

echo "[7] Applying W4-001 neutral language fix..."
sed 's/clearly sufficient/sufficient under precedent/g' /tmp/integrated-step1.md > /tmp/integrated-step2.md

echo "[8] Updating internal cross-references (II→IV, III→V, IV→VI)..."

# Update cross-references to reflect renumbering
# Be careful with patterns - Section II becomes Section IV, etc.
sed -e 's/Section II\([^I]\)/Section IV\1/g' \
    -e 's/Section III\([^I]\)/Section V\1/g' \
    -e 's/(Section II\./(Section IV./g' \
    -e 's/(Section III\./(Section V./g' \
    -e 's/\[Section II\]/[Section IV]/g' \
    -e 's/\[Section III\]/[Section V]/g' \
    /tmp/integrated-step2.md > /tmp/integrated-step3.md

echo "[9] Adding document footer..."

{
  cat /tmp/integrated-step3.md
  echo ""
  echo "═══════════════════════════════════════════════════════════════════════════════"
  echo "                          END OF MEMORANDUM"
  echo "═══════════════════════════════════════════════════════════════════════════════"
  echo ""
  echo "RESEARCH SUMMARY DISCLAIMER: This document is a research summary generated by"
  echo "an AI legal research platform. It is NOT legal advice from a licensed attorney."
  echo "All findings require independent verification by qualified legal counsel."
  echo ""
} > final-memorandum-v2.md

echo "[10] Verification..."
echo "Lines: $(wc -l < final-memorandum-v2.md)"
echo "Words: $(wc -w < final-memorandum-v2.md)"
echo ""
echo "Section headers:"
grep -n "^## [IV][IV]*\." final-memorandum-v2.md | head -10
echo ""
echo "Cross-reference check (should be 0):"
echo "  Old 'Section II' refs: $(grep -c 'Section II\.' final-memorandum-v2.md || echo 0)"
echo "  Old 'Section III' refs: $(grep -c 'Section III\.' final-memorandum-v2.md || echo 0)"
echo ""
echo "Integration complete!"

