#!/bin/bash

set -e
cd "/Users/ej/Super-Legal/super-legal-mcp-refactored/reports/2026-01-22-1737576000"

echo "=== Rebuilding final-memorandum-v2.md with correct structure ==="

# Start from W3-XREF base
cp remediation-outputs/W3-XREF-INSERT-final-memorandum-xrefs.md /tmp/base.md

echo "[1] Extracting components from base..."

# Header: lines 1-174 (title, TOC)
sed -n '1,174p' /tmp/base.md > /tmp/header.txt

# OLD Section II (Aggregate Risk): lines 242-371
sed -n '242,371p' /tmp/base.md > /tmp/old-agg-risk.txt

# OLD Section III (Critical Issues Matrix): lines 372-745
sed -n '372,745p' /tmp/base.md > /tmp/old-matrix.txt

# OLD Section IV+ (Detailed Analysis): lines 746-end
sed -n '746,$p' /tmp/base.md > /tmp/old-detailed.txt

echo "[2] Building new structure..."

{
  # Header (title page, TOC)
  cat /tmp/header.txt
  
  echo ""
  echo "## I. EXECUTIVE SUMMARY / BOARD BRIEFING"
  echo ""
  
  # Insert W4-002 - entire content as-is since it's already structured as subsections
  # Remove first 12 lines (title block) and last 15 lines (end markers/stats)
  sed -n '13,$p' remediation-outputs/W4-002-exec-summary-condensed.md | head -n -15
  
  echo ""
  echo "---"
  echo ""
  
  # NEW Section II: Questions Presented
  echo "## II. QUESTIONS PRESENTED"
  echo ""
  sed -n '12,$p' remediation-outputs/W2-001-questions-presented.md
  echo ""
  echo "---"
  echo ""
  
  # NEW Section III: Brief Answers
  echo "## III. BRIEF ANSWERS"
  echo ""
  sed -n '7,$p' remediation-outputs/W2-002-brief-answers.md
  echo ""
  echo "---"
  echo ""
  
  # RENUMBERED Section IV: Aggregate Risk (was II)
  echo "## IV. AGGREGATE RISK SUMMARY"
  echo ""
  tail -n +2 /tmp/old-agg-risk.txt
  echo ""
  echo "---"
  echo ""
  
  # RENUMBERED Section V: Critical Issues Matrix (was III)
  echo "## V. CRITICAL ISSUES MATRIX"
  echo ""
  tail -n +2 /tmp/old-matrix.txt
  echo ""
  echo "---"
  echo ""
  
  # RENUMBERED Section VI: Detailed Legal Analysis (was IV)
  echo "## VI. DETAILED LEGAL ANALYSIS"
  echo ""
  tail -n +2 /tmp/old-detailed.txt
  
} > /tmp/v2-rebuilt.md

echo "[3] Applying W4-001 neutral language..."
sed 's/clearly sufficient/sufficient under precedent/g' /tmp/v2-rebuilt.md > /tmp/v2-w4.md

echo "[4] Updating cross-references (II→IV, III→V, IV→VI)..."

# Use word boundaries to avoid changing "IV.A" etc.
sed -e 's/\([Ss]ection \)II\./\1IV./g' \
    -e 's/\([Ss]ection \)III\./\1V./g' \
    -e 's/(Section II\./(Section IV./g' \
    -e 's/(Section III\./(Section V./g' \
    /tmp/v2-w4.md > /tmp/v2-xref.md

echo "[5] Adding footer..."

{
  cat /tmp/v2-xref.md
  echo ""
  echo "═══════════════════════════════════════════════════════════════════════════════"
  echo "                          END OF MEMORANDUM"
  echo "═══════════════════════════════════════════════════════════════════════════════"
  echo ""
  echo "RESEARCH SUMMARY DISCLAIMER: This document is a research summary generated by"
  echo "an AI legal research platform. It is NOT legal advice from a licensed attorney."
  echo "All findings require independent verification by qualified legal counsel."
} > final-memorandum-v2.md

echo ""
echo "=== COMPLETE ==="
wc -lw final-memorandum-v2.md
echo ""
echo "Section structure:"
grep -n "^## [IVX]*\." final-memorandum-v2.md | head -20
echo ""
echo "Done!"

