#!/bin/bash

set -e
cd "/Users/ej/Super-Legal/super-legal-mcp-refactored/reports/2026-01-22-1737576000"

echo "=== Final Integration of final-memorandum-v2.md ==="

# Base file
cp remediation-outputs/W3-XREF-INSERT-final-memorandum-xrefs.md /tmp/base.md

echo "[1] Extracting base components..."
sed -n '1,174p' /tmp/base.md > /tmp/header.txt
sed -n '242,371p' /tmp/base.md > /tmp/old-sec-II.txt
sed -n '372,745p' /tmp/base.md > /tmp/old-sec-III.txt
sed -n '746,$p' /tmp/base.md > /tmp/old-sec-IV.txt

echo "[2] Assembling new document..."

{
  cat /tmp/header.txt
  
  echo ""
  echo "## I. EXECUTIVE SUMMARY / BOARD BRIEFING"
  echo ""
  
  # W4-002: lines 13-457 (skip header, keep until before END markers)
  sed -n '13,457p' remediation-outputs/W4-002-exec-summary-condensed.md
  
  echo ""
  echo "---"
  echo ""
  
  # Questions Presented (W2-001)
  echo "## II. QUESTIONS PRESENTED"
  echo ""
  sed -n '12,$p' remediation-outputs/W2-001-questions-presented.md
  echo ""
  echo "---"
  echo ""
  
  # Brief Answers (W2-002)
  echo "## III. BRIEF ANSWERS"
  echo ""
  sed -n '7,$p' remediation-outputs/W2-002-brief-answers.md
  echo ""
  echo "---"
  echo ""
  
  # Section IV: Aggregate Risk (renumbered from II)
  echo "## IV. AGGREGATE RISK SUMMARY"
  echo ""
  tail -n +2 /tmp/old-sec-II.txt
  echo ""
  echo "---"
  echo ""
  
  # Section V: Critical Issues Matrix (renumbered from III)
  echo "## V. CRITICAL ISSUES MATRIX"
  echo ""
  tail -n +2 /tmp/old-sec-III.txt
  echo ""
  echo "---"
  echo ""
  
  # Section VI: Detailed Analysis (renumbered from IV)
  echo "## VI. DETAILED LEGAL ANALYSIS"
  echo ""
  tail -n +2 /tmp/old-sec-IV.txt
  
} > /tmp/assembled.md

echo "[3] Applying W4-001 neutral language..."
sed 's/clearly sufficient/sufficient under precedent/g' /tmp/assembled.md > /tmp/neutralized.md

echo "[4] Updating cross-references..."
sed -e 's/\(Section \)II\(\.[^A-Z]\)/\1IV\2/g' \
    -e 's/\(Section \)III\(\.[^A-Z]\)/\1V\2/g' \
    -e 's/(Section II\./(Section IV./g' \
    -e 's/(Section III\./(Section V./g' \
    /tmp/neutralized.md > /tmp/xref-fixed.md

echo "[5] Adding footer..."

{
  cat /tmp/xref-fixed.md
  echo ""
  echo "═══════════════════════════════════════════════════════════════════════════════"
  echo "                          END OF MEMORANDUM"
  echo "═══════════════════════════════════════════════════════════════════════════════"
  echo ""
  echo "RESEARCH SUMMARY DISCLAIMER: This document is a research summary generated by"
  echo "an AI legal research platform. It is NOT legal advice from a licensed attorney."
  echo "All findings require independent verification by qualified legal counsel."
} > final-memorandum-v2.md

echo ""
echo "=== VERIFICATION ==="
wc -lw final-memorandum-v2.md
echo ""
echo "Main sections:"
grep -n "^## [IVX]*\." final-memorandum-v2.md | grep -v "^[0-9]*:###" | head -25
echo ""
echo "Complete!"

