#!/bin/bash

# Simple assembly script - concatenate files with proper headers
OUTPUT="final-memorandum.md"

# Assembly metadata
cat > "$OUTPUT" << 'METADATA'
<!-- ASSEMBLY METADATA
Generated: 2026-01-03T18:00:00Z
Session: 2025-12-10-1765324800
Sections: 12 + Executive Summary
Citations: 2,012 (inline verification tags)
Status: ASSEMBLED
-->

METADATA

# Title page
cat >> "$OUTPUT" << 'TITLE'
PRIVILEGED AND CONFIDENTIAL
ATTORNEY WORK PRODUCT

MEMORANDUM OF LAW

TO:         Atlas Power Holdings Investment Committee
FROM:       Legal Research Platform
DATE:       January 3, 2026
RE:         Project Prometheus - $3.2B Great Lakes Nuclear Acquisition
            Due Diligence Memorandum

---

TITLE

# Add executive summary
cat executive-summary.md >> "$OUTPUT"

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Add each section in order
for section in section-reports/section-IV-{A,B,C,D,E,F,G,H,I,J,K,L}-*.md; do
    echo "Adding $(basename $section)..."
    echo "" >> "$OUTPUT"
    cat "$section" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "---" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
done

# Add footer
cat >> "$OUTPUT" << 'FOOTER'

RESEARCH SUMMARY DISCLAIMER: This document is a research summary generated by an AI legal research platform. It is NOT legal advice from a licensed attorney. All findings require independent verification by qualified legal counsel before reliance. This output is intended to assist, not replace, professional legal judgment.
FOOTER

# Count words
WORD_COUNT=$(grep -o '\w\+' "$OUTPUT" | wc -l)
echo ""
echo "✓ Assembly complete!"
echo "  Word count: $WORD_COUNT"
echo "  Output: $OUTPUT"

